name: Deploy React App to Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build and Deploy React App
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Where am i 
        run: pwd && ls

      - name: Copied Static Files to Docs folder
        # Serve the file
        run: cp -r ./build ./docs

      - name: Cleanup Build folder
        run: rm -r ./build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: ./build

      - name: Echo Finish
        run: echo Finish Deployment
  